### ISSUE TITLE
packing a folder

### ISSUE THREAD

**Issue by wither735** [panzi/rust-u4pak#35]
Yeah, sorry I am stupid but how can I make this folder into a .pak file I tried it for 4 hours and i coudnt figure it out. So here I am now asking for help (I don't have Python installed)

![Screenshot (75)](https://user-images.githubusercontent.com/89296018/215360381-cdce1d44-e51c-4f40-8706-cc72cc2c1707.png)

**Comment by panzi** [comment]
Since you don't have Python you can use [rust-u4pak ](https://github.com/panzi/rust-u4pak) for which I provide compiled binaries: https://github.com/panzi/rust-u4pak/releases/tag/v1.3.0

To pack a folder put u4pak.exe into `%PATH%` (e.g. `C:\Windows\System32` I think; I haven't used Windows in probably almost 20 years) and then do:

```
u4pak.exe pack --mount-point=../../.. --version=4 "G:\Wherever\You\Want\The\Result.pak" ":rename=/:G:\Programme\Epic Games\Old Fortnite\MOD\u4pak\release-v1.3.0\x86_64-pc-windows-gnu\FortniteGame"
```

I neither know what the correct `--mount-point` not the correct `--version` is for Fortnite. Use `u4pak.exe info "G:\Path\To\Original\Archive.pak"` to find that out. Also I don't know what the file system of Fortnite's archive is supposed to look like, so you might need a rename command, maybe `:rename=/FortniteGame:`? Depends on how you dumped that folder. I don't know anything about Fortnite, didn't even know it uses Unreal Engine 4.

If you don't want to keep typing these things into `cmd.exe` you can put it into a `.bat` file or use `.u4pak` files as described in the README. (You can somehow associate `.u4pak` files to be always automatically be opened with `u4pak.exe` somehow. Again, didn't use Windows in a long time.) You probably want to use `--pause-on-exit=auto` so the terminal window stays open after execution so you have a chance to see the output (in case there was an error).

**Comment by wither735** [comment]
Hello when i try to Use **u4pak.exe info "G:\Path\To\Original\Archive.pak"** i always get this error 
![Screenshot (76)](https://user-images.githubusercontent.com/89296018/215423401-f03894d3-625f-4efb-b3ac-ad671466740d.png)

**Comment by Xenira** [comment]
Looks like that game is using chunked pak files.
Those are not supported afaik. I started working on them, but had a lot going on, so was not able to finish that.

Please provide a list of files located in the Content directory and the UE4 version used.

**Comment by wither735** [comment]
I now got a Result.pak file I used this command: **u4pak.exe pack --mount-point=../../.. --version=4 "G:\Wherever\You\Want\The\Result.pak" ":rename=/:G:\Programme\Epic Games\Old Fortnite\MOD\u4pak\release-v1.3.0\x86_64-pc-windows-gnu\FortniteGame"** but i changed the path a bit so it matches with my files and i used Version 1 instead of 4 **And i use Unreal Engine 4.22.3**

![Screenshot (77)](https://user-images.githubusercontent.com/89296018/215427662-0573cf4e-701d-41b7-a73e-44605afd2c8c.png)
![Screenshot (78)](https://user-images.githubusercontent.com/89296018/215427667-5f9d909b-1ac1-4d56-9a60-b46d475c82d5.png)

**Comment by Xenira** [comment]
If you have a look at the Readme you will notice, that creating pak files for file version 8 (that should be the one used for 4.22.3) is not yet supported.

**Comment by wither735** [comment]
Is it also ok if I use version 1 (that's what I used)

**Comment by Xenira** [comment]
I am not 100% sure (there is some code to load older pak files) but I would say no.
Maybe if you repack everything into a supported format it works, but I have no idea.

**Comment by wither735** [comment]
hmm ok thanks i will try
